--看全部執行結果
SELECT *
FROM AUTO_TEST.TB_CIFX_AUTO_TEST_RESULT_OCP
ORDER BY TX_DATE DESC
;



--看java執行結果
SELECT *
FROM AUTO_TEST.TB_CIFX_AUTO_TEST_RESULT_OCP
WHERE CASE_ID IN ('TS0116-queryCustContact-0001')
ORDER BY TX_DATE DESC
;



-- --==================平行查看CASE 與執行結果================
SELECT
--CASEE.*
-- RT.*
CASEE.CASE_ID,
RT.IS_PASS,
RT.ERROR_MESSAGE,
CASEE.VERIFY_RULE,
CASEE.REQUEST_BODY,
CASEE.VERIFY_RULE AS EXPECTED_VALUE,
CASEE.PATH        AS URL_PATH,
RT.RESULT_CODE    AS ACUTAL_VALUE

FROM AUTO_TEST.TB_CIFX_AUTO_TEST_CASE_OCP CASEE
         JOIN AUTO_TEST.TB_CIFX_AUTO_TEST_RESULT_OCP RT ON CASEE.CASE_ID = RT.CASE_ID
WHERE 1 = 1
-- AND CASEE.TEST_GROUP = 'CIFX_RJ'
--AND RT.IS_PASS = 'F'
  AND CASEE.CASE_ID = 'TS0116-updateSmsPasswordForDigital-0001'
ORDER BY RT.TX_DATE DESC;
;


--============================================
