


--step1
--清空TABLE 資料
TRUNCATE TABLE CIFX_BATCH.TB_BT_CIFIX;
/

--step2
-- 塞入建檔單位與主經營行資料
INSERT
INTO CIFX_BATCH.TB_BT_CIFIX(CIF_VERIFIED_ID, COLUMN_NAME, COLUMN_CHANGED_VALUE, CHECK_CHANGE_LOG, CHECK_SPECIFIC_RULES, CHECK_BEFORE_VALUE, WRITE_LOG_FLAG, TO_CIP_FLAG, PUSH_FLAG, REQ_NO)

--=====  1263 to 1089 start ===========
--建檔單位
SELECT
CIF_VERIFIED_ID,
'CREATION_DPT_CODE' AS COLUMN_NAME,
CASE
WHEN
CREATION_DPT_CODE IN ('1263') THEN '1089'
END AS COLUMN_CHANGE_VALUE,

NULL AS CHECK_CHANGE_LOG,
NULL AS CHECK_SPECIFIC_RULES,
CREATION_DPT_CODE AS CHECK_BEFORE_VALUE,
'Y' AS WRITE_LOG_FLAG,
NULL AS TO_CIP_FLAG,
NULL AS PUSH_FLAG,
'EW2022012800022' AS REQ_NO
FROM CIFX.TB_CUSTOMER
WHERE CREATION_DPT_CODE IN('1263')

union all

--主經營行
SELECT
CIF_VERIFIED_ID,
'PERFORMANCE_DPT_CODE' AS COLUMN_NAME,
CASE
WHEN PERFORMANCE_DPT_CODE IN ('1263') THEN '1089'
END AS COLUMN_CHANGE_VALUE,
NULL AS CHECK_CHANGE_LOG,
NULL AS CHECK_SPECIFIC_RULES,
PERFORMANCE_DPT_CODE AS CHECK_BEFORE_VALUE,
'Y' AS WRITE_LOG_FLAG,
NULL AS TO_CIP_FLAG,
NULL AS PUSH_FLAG,
'EW2022012800022' AS REQ_NO
FROM CIFX.TB_CUSTOMER
WHERE PERFORMANCE_DPT_CODE IN('1263');
--=====  1263 to 1089 end ===========

COMMIT;
/


--step3
--確認TABLE 內是否有值約  21994 筆
SELECT COUNT(1) FROM CIFX_BATCH.TB_BT_CIFIX;
/


--step4
--執行以下SQL 變更
DECLARE
v_file_name varchar2(20) := 'BTCIFIX';
v_table_name varchar2(20):= 'TB_BT_CIFIX';
v_job_no varchar2(20) := null;
o_job_no varchar2(20);
o_ok_num varchar2(20);
o_fail_num varchar2(20);
o_return varchar2(20);
BEGIN
CIFX_BATCH.SP_BT_CIFIX(
v_file_name,
v_table_name,
v_job_no,
o_job_no,
o_ok_num,
o_fail_num,
o_return
);
END;
/

--step5
--執行結束後驗證RUN_RESULT NULL筆數為0(若不為0請通知AP經辦)
SELECT COUNT(1) FROM CIFX_BATCH.TB_BT_CIFIX WHERE RUN_RESULT IS NULL;
/


--step6
--若以上步驟皆無問題執行以下SQL並匯出成CSV並加密附於單上
SELECT ALL_DATA FROM CIFX_BATCH.TB_BT_CIFIX_OUT ORDER BY SEQ_NO;
/

