--自定義EXCEPTION
INNER_NO_DATA_FOUND_EXCEPTION EXCEPTION;

--自拋
IF CONDITION THEN
RAISE INNER_NO_DATA_FOUND_EXCEPTION;
END IF;

.....

--自接
EXCEPTION
    WHEN INNER_NO_DATA_FOUND_EXCEPTION THEN
........;
/
IF CONDITION THEN
RAISE_APPLICATION_ERROR(-20001,'至少輸入一個可查詢參數');
END IF;

EXCEPTION
    WHEN OTHERS THEN  --所產生自定例外沒有命名，只能利用OTHERS
    DBMS_OUTPUT.PUT_LINE( '錯誤: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE || DBMS_UTILITY.FORMAT_ERROR_STACK );
....
END;
/
