--------------------------------------------------------
--  已建立檔案 - 星期六-十二月-11-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_SYS_COL_ACT
--------------------------------------------------------

  CREATE TABLE "CIFX"."TB_SYS_COL_ACT" 
   (	"SYS_COL_ID" NUMBER(*,0), 
	"SENDER_CODE" VARCHAR2(20 CHAR), 
	"ACT_TYPE" VARCHAR2(10 CHAR), 
	"IO_TYPE" VARCHAR2(20 CHAR), 
	"IDENTIFIER_CODE" VARCHAR2(100 CHAR), 
	"COLUMN_CODE" VARCHAR2(10 CHAR), 
	"PSEUDO_COLUMN" VARCHAR2(100 CHAR), 
	"QUERY_OUTPUT_JSON_NAME" VARCHAR2(100 CHAR), 
	"UPDATE_INPUT_JSON_NAME" VARCHAR2(100 CHAR)
   ) ;

   COMMENT ON COLUMN "CIFX"."TB_SYS_COL_ACT"."SYS_COL_ID" IS '流水號';
   COMMENT ON COLUMN "CIFX"."TB_SYS_COL_ACT"."SENDER_CODE" IS '系統代碼';
   COMMENT ON COLUMN "CIFX"."TB_SYS_COL_ACT"."ACT_TYPE" IS '行為種類
(Q:查詢
U:異動)';
   COMMENT ON COLUMN "CIFX"."TB_SYS_COL_ACT"."IO_TYPE" IS '輸入/輸出';
   COMMENT ON COLUMN "CIFX"."TB_SYS_COL_ACT"."IDENTIFIER_CODE" IS '識別條件組合
';
   COMMENT ON COLUMN "CIFX"."TB_SYS_COL_ACT"."COLUMN_CODE" IS '欄位代碼';
   COMMENT ON COLUMN "CIFX"."TB_SYS_COL_ACT"."PSEUDO_COLUMN" IS '虛擬欄位';
   COMMENT ON COLUMN "CIFX"."TB_SYS_COL_ACT"."QUERY_OUTPUT_JSON_NAME" IS '查詢回傳JSON欄位名稱';
   COMMENT ON COLUMN "CIFX"."TB_SYS_COL_ACT"."UPDATE_INPUT_JSON_NAME" IS '異動輸入JSON欄位名稱';

SET DEFINE OFF;
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (36,'TS0077','U',null,null,'X0234',null,null,'permanentPhoneNumber');
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (37,'TS0077','U',null,null,'X0128',null,null,'residentialPhoneNumber');
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (99,'TS0116','Q','O','TS0116@01','X0110',null,'customerCirciKey',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (1,'TS0077','Q','I','TS0077@03','X0110',null,'customerCirciKey',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (2,'TS0077','Q','I','TS0077@01','X0103',null,'birthday',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (3,'TS0077','Q','I','TS0077@02',null,'accountNumber',null,null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (4,'TS0077','Q','I','TS0077@01','X0109',null,'customerCertificationNumber',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (5,'TS0077','Q','O',null,'X0109',null,'customerCertificationNumber',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (6,'TS0077','Q','O',null,'X0240',null,'stopUsingCustomerDataFlag',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (7,'TS0077','Q','O',null,'X0251',null,'wiseCustomer',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (8,'TS0077','Q','O',null,'X0142',null,'customerType',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (9,'TS0077','Q','O',null,'X0220',null,'customerPropertyType',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (10,'TS0077','Q','O',null,'E0001',null,'checkCollectionFee',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (11,'TS0077','Q','O',null,'E0002',null,'blankCheckFee',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (12,'TS0077','Q','O',null,'E0003',null,'interBankRemittanceFee',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (13,'TS0077','Q','O',null,'X0110',null,'customerCirciKey',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (14,'TS0077','Q','O',null,'X0103',null,'birthday',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (15,'TS0077','Q','O',null,'X0143',null,'customerName',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (16,'TS0077','Q','O',null,'X0244',null,'terroristsFlag',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (17,'TS0077','Q','O',null,'X0239',null,'specialAccountFlag',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (18,'TS0077','Q','O',null,'X0141',null,'customerStatus',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (19,'TS0077','Q','O',null,'X0226',null,'caseReportedDate',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (20,'TS0077','Q','O',null,'X0228',null,'reportUnit',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (21,'TS0077','Q','O',null,'X0137',null,'caseCreatedDepartment',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (22,'TS0077','Q','O',null,'X0227',null,'caseDescription',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (23,'TS0077','Q','O',null,'X0096',null,'accountReviewStateFlag',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (24,'TS0077','Q','O',null,'X0095',null,'accountReviewPendingFlag',null);
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (34,'TS0077','U',null,null,'X0157',null,null,'emailSellingFlag');
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (33,'TS0077','U',null,null,'X0114',null,null,'mobilePhoneNumber');
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (38,'TS0077','U',null,null,'X0150',null,null,'industrialCodeForDgbas');
Insert into CIFX.TB_SYS_COL_ACT (SYS_COL_ID,SENDER_CODE,ACT_TYPE,IO_TYPE,IDENTIFIER_CODE,COLUMN_CODE,PSEUDO_COLUMN,QUERY_OUTPUT_JSON_NAME,UPDATE_INPUT_JSON_NAME) values (35,'TS0077','Q','O',null,'X0256',null,'customerKycType',null);
--------------------------------------------------------
--  DDL for Index SYS_C00250418
--------------------------------------------------------

  CREATE UNIQUE INDEX "CIFX"."SYS_C00250418" ON "CIFX"."TB_SYS_COL_ACT" ("SYS_COL_ID") 
  ;
--------------------------------------------------------
--  Constraints for Table TB_SYS_COL_ACT
--------------------------------------------------------

  ALTER TABLE "CIFX"."TB_SYS_COL_ACT" MODIFY ("SYS_COL_ID" NOT NULL ENABLE);
  ALTER TABLE "CIFX"."TB_SYS_COL_ACT" ADD PRIMARY KEY ("SYS_COL_ID")
  USING INDEX  ENABLE;
