
-- SP_CHG_CUST_TYPE
-- set serveroutputon;
-- SET DEFINE OFF;
DECLARE

V_MES_NUM VARCHAR2(999 CHAR):= 'TS0108TS0077202107309999 050007';
V_TRA_SEQ VARCHAR2(999 CHAR):= 'A102011';
V_TRA_DAT_TIM  VARCHAR2(999 CHAR):= '20211026 101600';
V_SEN_COD  VARCHAR2(999 CHAR):= 'TS0108';
V_REC_COD  VARCHAR2(999 CHAR):= 'TS0116';
V_TEL_EMP_NUM  VARCHAR2(999 CHAR):= '97132';
V_PRO_UNI VARCHAR2(999 CHAR):= '9999';
V_SUP_EMP_NUM VARCHAR2(999 CHAR):= '';
V_FUN_ID  VARCHAR2(999 CHAR):= '02';
V_EDLS_ORI_TRADE_SEQ_NO     TB_CHANGE_LOG.EDLS_ORI_TRADE_SEQ_NO%TYPE := '050007';
V_EDLS_SOURCE_CODE           TB_CHANGE_LOG.EDLS_SOURCE_CODE%TYPE:= 'TS0077';
V_EDLS_SUPERVISOR_CARD_CODE  TB_CHANGE_LOG.SUPERVISOR_CARD_CODE%TYPE:= '';
V_CIR_KEY  VARCHAR2(999 CHAR):= '&I65544799';
V_CUS_TYP_COD VARCHAR2(999 CHAR):= '04';

V_RES_COD  VARCHAR2(999 CHAR):= '';
V_RES_DES  VARCHAR2(999 CHAR):= '';
V_ERR_MES  VARCHAR2(999 CHAR):= '';

BEGIN

DBMS_OUTPUT.PUT_LINE('======== TEST START =========');
CIFX.PG_CIFX_TO_EDLS_EXE.SP_CHG_CUST_TYPE(
I_MES_NUM  => V_MES_NUM,
I_TRA_SEQ => V_TRA_SEQ,
I_TRA_DAT_TIM  => V_TRA_DAT_TIM,
I_SEN_COD => V_SEN_COD,
I_REC_COD => V_REC_COD,
I_TEL_EMP_NUM => V_TEL_EMP_NUM,
I_PRO_UNI  => V_PRO_UNI,
I_SUP_EMP_NUM  => V_SUP_EMP_NUM,
I_FUN_ID  => V_FUN_ID,
I_EDLS_ORI_TRADE_SEQ_NO    => V_EDLS_ORI_TRADE_SEQ_NO,
I_EDLS_SOURCE_CODE         => V_EDLS_SOURCE_CODE,
I_EDLS_SUPERVISOR_CARD_CODE => V_EDLS_SUPERVISOR_CARD_CODE,
I_CIR_KEY  => V_CIR_KEY,
I_CUS_TYP_COD  => V_CUS_TYP_COD,
O_RES_COD  => V_RES_COD,
O_RES_DES  => V_RES_DES,
O_ERR_MES  => V_ERR_MES
);

DBMS_OUTPUT.PUT_LINE('V_RES_COD:'||V_RES_COD);
DBMS_OUTPUT.PUT_LINE('V_RES_DES:'||V_RES_DES);
DBMS_OUTPUT.PUT_LINE('V_ERR_MES:'||V_ERR_MES);

DBMS_OUTPUT.PUT_LINE('======== TEST END =========');
END;
