--異動前
SELECT CLL.CHANGE_LOG_ID,
       CLL.SENt_TIMESTAMP
FROM CIFX.TB_CHANGE_LOG CL
         JOIN CIFX.TB_CHANGE_LOG_LINEITEM CLL ON CL.CHANGE_LOG_ID = CLL.CHANGE_LOG_ID
         JOIN CIFX.TB_SERVICE_EXECUTION_CONTROL SEC ON SEC.SERVICE_INTERCHANGE_ID = CL.SERVICE_INTERCHANGE_ID
WHERE SEC.SERVICE_INTERCHANGE_ID IN (
    '1625858228376864-2250446-02-02'
    )
  and sec.execution_type = 'STAGE1_EXECUTION'
ORDER BY CLL.CREATE_TIMESTAMP DESC;
/


--執行異動
update cifx.tb_change_log_lineitem cll
set cll.sent_timestamp = null
where cll.change_log_id in (
    SELECT CLL.CHANGE_LOG_ID
    FROM CIFX.TB_CHANGE_LOG CL
             JOIN CIFX.TB_CHANGE_LOG_LINEITEM CLL ON CL.CHANGE_LOG_ID = CLL.CHANGE_LOG_ID
             JOIN CIFX.TB_SERVICE_EXECUTION_CONTROL SEC ON SEC.SERVICE_INTERCHANGE_ID = CL.SERVICE_INTERCHANGE_ID
    WHERE SEC.SERVICE_INTERCHANGE_ID IN (
        '1647500157066911-8392796-56-01'
        )
      and sec.execution_type = 'STAGE1_EXECUTION'
);
/

COMMIT;
/


--異動後
SELECT CLL.CHANGE_LOG_ID,
       CLL.SENt_TIMESTAMP
FROM CIFX.TB_CHANGE_LOG CL
         JOIN CIFX.TB_CHANGE_LOG_LINEITEM CLL ON CL.CHANGE_LOG_ID = CLL.CHANGE_LOG_ID
         JOIN CIFX.TB_SERVICE_EXECUTION_CONTROL SEC ON SEC.SERVICE_INTERCHANGE_ID = CL.SERVICE_INTERCHANGE_ID
WHERE SEC.SERVICE_INTERCHANGE_ID IN (
    '1625858228376864-2250446-02-02'
    )
  and sec.execution_type = 'STAGE1_EXECUTION'
ORDER BY CLL.CREATE_TIMESTAMP DESC;
/


SELECT EXECUTION_TYPE, SERVICE_INTERCHANGE_ID, CIRCI_KEY, EXECUTION_STATE
FROM CIFX.TB_SERVICE_EXECUTION_CONTROL
WHERE SERVICE_EXECUTION_CONTROL_ID IN ('1633339030268685-9464925-21-01')
  AND EXECUTION_TYPE = 'STAGE1_EXECUTION';


UPDATE CIFX.TB_SERVICE_EXECUTION_CONTROL
SET EXECUTION_STATE     = 'TO_EXECUTE',
    RESULT_CODE         = NULL,
    EXECUTING_TIMESTAMP = null,
    EXECUTED_TIMESTAMP  = null,
    ap_server_EXECUTING = NULL
WHERE SERVICE_EXECUTION_CONTROL_ID IN ('1633339030268685-9464925-21-01')
  AND EXECUTION_TYPE = 'STAGE1_EXECUTION';


SELECT EXECUTION_TYPE, SERVICE_INTERCHANGE_ID, CIRCI_KEY, EXECUTION_STATE
FROM CIFX.TB_SERVICE_EXECUTION_CONTROL
WHERE SERVICE_EXECUTION_CONTROL_ID IN ('1633339030268685-9464925-21-01')
  AND EXECUTION_TYPE = 'STAGE1_EXECUTION';
