--透過  116  插入資料列  1  失敗
--ORA-00001: 違反必須為唯一的限制條件 (CIFX_BATCH.TT_ADDR_MAPPING_PK)
--資料列 1
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (1,'福善里','36','永和路67號','永和路81號');
--資料列 2
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (2,'福善里','36','永和路67號二樓','永和路81號二樓');
--資料列 3
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (3,'福善里','36','永和路67號三樓','永和路81號三樓');
--資料列 4
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (4,'福善里','36','永和路67號四樓','永和路81號四樓');
--資料列 5
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (5,'福善里','36','永和路67號五樓','永和路81號五樓');
--資料列 6
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (6,'福善里','36','永和路67號六樓','永和路81號六樓');
--資料列 7
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (7,'福善里','36','永和路67號七樓','永和路81號七樓');
--資料列 8
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (8,'福善里','36','永和路67之1號','永和路83號');
--資料列 9
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (9,'福善里','36','永和路67之1號二樓','永和路83號二樓');
--資料列 10
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (10,'福善里','36','永和路67之1號三樓','永和路83號三樓');
--資料列 11
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (11,'福善里','36','永和路67之1號四樓','永和路83號四樓');
--資料列 12
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (12,'福善里','36','永和路67之1號五樓','永和路83號五樓');
--資料列 13
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (13,'福善里','36','永和路67之1號六樓','永和路83號六樓');
--資料列 14
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (14,'福善里','36','永和路67之1號七樓','永和路83號七樓');
--資料列 15
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (15,'福善里','36','永和路67之2號','永和路85號');
--資料列 16
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (16,'福善里','36','永和路67之2號二樓','永和路85號二樓');
--資料列 17
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (17,'福善里','36','永和路67之2號三樓','永和路85號三樓');
--資料列 18
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (18,'福善里','36','永和路67之2號四樓','永和路85號四樓');
--資料列 19
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (19,'福善里','36','永和路67之2號五樓','永和路85號五樓');
--資料列 20
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (20,'福善里','36','永和路67之2號六樓','永和路85號六樓');
--資料列 21
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (21,'福善里','36','永和路67之2號七樓','永和路85號七樓');
--資料列 22
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (22,'福善里','33','永和路69號','永和路87號');
--資料列 23
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (23,'福善里','33','永和路69號二樓','永和路87號二樓');
--資料列 24
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (24,'福善里','33','永和路69號三樓','永和路87號三樓');
--資料列 25
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (25,'福善里','33','永和路69號四樓','永和路87號四樓');
--資料列 26
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (26,'福善里','33','永和路69號五樓','永和路87號五樓');
--資料列 27
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (27,'福善里','33','永和路69之1號','永和路89號');
--資料列 28
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (28,'福善里','33','永和路69之1號二樓','永和路89號二樓');
--資料列 29
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (29,'福善里','33','永和路69之1號三樓','永和路89號三樓');
--資料列 30
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (30,'福善里','33','永和路69之1號四樓','永和路89號四樓');
--資料列 31
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (31,'福善里','33','永和路69之1號五樓','永和路89號五樓');
--資料列 32
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (32,'福善里','33','永和路69之2號','永和路91號');
--資料列 33
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (33,'福善里','33','永和路69之2號二樓','永和路91號二樓');
--資料列 34
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (34,'福善里','33','永和路69之2號三樓','永和路91號三樓');
--資料列 35
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (35,'福善里','33','永和路69之2號四樓','永和路91號四樓');
--資料列 36
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (36,'福善里','33','永和路69之2號五樓','永和路91號五樓');
--資料列 37
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (37,'福善里','33','永和路69之3號','永和路93號');
--資料列 38
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (38,'福善里','33','永和路69之3號二樓','永和路93號二樓');
--資料列 39
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (39,'福善里','33','永和路69之3號三樓','永和路93號三樓');
--資料列 40
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (40,'福善里','33','永和路69之3號四樓','永和路93號四樓');
--資料列 41
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (41,'福善里','33','永和路69之3號五樓','永和路93號五樓');
--資料列 42
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (42,'福善里','33','永和路69之4號','永和路95號');
--資料列 43
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (43,'福善里','33','永和路69之4號二樓','永和路95號二樓');
--資料列 44
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (44,'福善里','33','永和路69之4號三樓','永和路95號三樓');
--資料列 45
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (45,'福善里','33','永和路69之4號四樓','永和路95號四樓');
--資料列 46
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (46,'福善里','33','永和路69之4號五樓','永和路95號五樓');
--資料列 47
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (47,'福善里','33','永和路69之5號','永和路97號');
--資料列 48
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (48,'福善里','33','永和路69之5號二樓','永和路97號二樓');
--資料列 49
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (49,'福善里','33','永和路69之5號三樓','永和路97號三樓');
--資料列 50
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (50,'福善里','33','永和路69之5號四樓','永和路97號四樓');
--資料列 51
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (51,'福善里','33','永和路69之5號五樓','永和路97號五樓');
--資料列 52
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (52,'福善里','32','永和路69巷1號','永和路99巷1號');
--資料列 53
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (53,'福善里','32','永和路69巷1號二樓','永和路99巷1號二樓');
--資料列 54
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (54,'福善里','32','永和路69巷1號三樓','永和路99巷1號三樓');
--資料列 55
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (55,'福善里','32','永和路69巷1號四樓','永和路99巷1號四樓');
--資料列 56
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (56,'福善里','32','永和路69巷1號五樓','永和路99巷1號五樓');
--資料列 57
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (57,'福善里','32','永和路69巷3號','永和路99巷3號');
--資料列 58
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (58,'福善里','32','永和路69巷3號二樓','永和路99巷3號二樓');
--資料列 59
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (59,'福善里','32','永和路69巷3號三樓','永和路99巷3號三樓');
--資料列 60
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (60,'福善里','32','永和路69巷3號四樓','永和路99巷3號四樓');
--資料列 61
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (61,'福善里','32','永和路69巷3號五樓','永和路99巷3號五樓');
--資料列 62
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (62,'福善里','32','永和路69巷5號','永和路99巷5號');
--資料列 63
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (63,'福善里','32','永和路69巷5號二樓','永和路99巷5號二樓');
--資料列 64
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (64,'福善里','32','永和路69巷5號三樓','永和路99巷5號三樓');
--資料列 65
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (65,'福善里','32','永和路69巷5號四樓','永和路99巷5號四樓');
--資料列 66
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (66,'福善里','32','永和路69巷5號五樓','永和路99巷5號五樓');
--資料列 67
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (67,'福善里','32','永和路69巷7號','永和路99巷7號');
--資料列 68
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (68,'福善里','32','永和路69巷7號二樓','永和路99巷7號二樓');
--資料列 69
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (69,'福善里','32','永和路69巷7號三樓','永和路99巷7號三樓');
--資料列 70
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (70,'福善里','32','永和路69巷7號四樓','永和路99巷7號四樓');
--資料列 71
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (71,'福善里','32','永和路69巷7號五樓','永和路99巷7號五樓');
--資料列 72
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (72,'福善里','32','永和路69巷9號','永和路99巷9號');
--資料列 73
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (73,'福善里','32','永和路69巷9號二樓','永和路99巷9號二樓');
--資料列 74
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (74,'福善里','32','永和路69巷9號三樓','永和路99巷9號三樓');
--資料列 75
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (75,'福善里','32','永和路69巷9號四樓','永和路99巷9號四樓');
--資料列 76
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (76,'福善里','32','永和路69巷9號五樓','永和路99巷9號五樓');
--資料列 77
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (77,'福善里','32','永和路69巷11號','永和路99巷11號');
--資料列 78
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (78,'福善里','32','永和路69巷11號二樓','永和路99巷11號二樓');
--資料列 79
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (79,'福善里','32','永和路69巷11號三樓','永和路99巷11號三樓');
--資料列 80
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (80,'福善里','32','永和路69巷11號四樓','永和路99巷11號四樓');
--資料列 81
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (81,'福善里','32','永和路69巷11號五樓','永和路99巷11號五樓');
--資料列 82
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (82,'福善里','37','永和路69之6號','永和路101號');
--資料列 83
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (83,'福善里','37','永和路69之6號二樓','永和路101號二樓');
--資料列 84
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (84,'福善里','37','永和路69之6號三樓','永和路101號三樓');
--資料列 85
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (85,'福善里','37','永和路69之6號四樓','永和路101號四樓');
--資料列 86
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (86,'福善里','37','永和路69之6號五樓','永和路101號五樓');
--資料列 87
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (87,'福善里','37','永和路69之6號六樓','永和路101號六樓');
--資料列 88
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (88,'福善里','37','永和路69之6號七樓','永和路101號七樓');
--資料列 89
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (89,'福善里','37','永和路69之7號二樓','永和路103號二樓');
--資料列 90
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (90,'福善里','37','永和路69之7號三樓','永和路103號三樓');
--資料列 91
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (91,'福善里','37','永和路69之7號四樓','永和路103號四樓');
--資料列 92
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (92,'福善里','37','永和路69之7號五樓','永和路103號五樓');
--資料列 93
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (93,'福善里','37','永和路69之7號六樓','永和路103號六樓');
--資料列 94
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (94,'福善里','37','永和路69之7號七樓','永和路103號七樓');
--資料列 95
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (95,'福善里','37','永和路69之8號','永和路105號');
--資料列 96
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (96,'福善里','37','永和路69之8號二樓','永和路105號二樓');
--資料列 97
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (97,'福善里','37','永和路69之8號三樓','永和路105號三樓');
--資料列 98
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (98,'福善里','37','永和路69之8號四樓','永和路105號四樓');
--資料列 99
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (99,'福善里','37','永和路69之8號五樓','永和路105號五樓');
--資料列 100
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (100,'福善里','37','永和路69之8號六樓','永和路105號六樓');
--資料列 101
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (101,'福善里','37','永和路69之8號七樓','永和路105號七樓');
--資料列 102
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (102,'福善里','37','永和路69之9號','永和路107號');
--資料列 103
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (103,'福善里','37','永和路69之9號二樓','永和路107號二樓');
--資料列 104
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (104,'福善里','37','永和路69之9號三樓','永和路107號三樓');
--資料列 105
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (105,'福善里','37','永和路69之9號四樓','永和路107號四樓');
--資料列 106
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (106,'福善里','37','永和路69之9號五樓','永和路107號五樓');
--資料列 107
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (107,'福善里','37','永和路69之9號六樓','永和路107號六樓');
--資料列 108
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (108,'福善里','37','永和路69之9號七樓','永和路107號七樓');
--資料列 109
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (109,'福善里','37','永和路69之10號','永和路109號');
--資料列 110
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (110,'福善里','37','永和路69之10號二樓','永和路109號二樓');
--資料列 111
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (111,'福善里','37','永和路69之10號三樓','永和路109號三樓');
--資料列 112
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (112,'福善里','37','永和路69之10號四樓','永和路109號四樓');
--資料列 113
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (113,'福善里','37','永和路69之10號五樓','永和路109號五樓');
--資料列 114
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (114,'福善里','37','永和路69之10號六樓','永和路109號六樓');
--資料列 115
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (115,'福善里','37','永和路69之10號七樓','永和路109號七樓');
--資料列 116
INSERT INTO TT_ADDR_MAPPING (UUID, OLD_LI, OLD_NB, OLD_ADDR, NEW_ADDR) VALUES (116,'中原里','16','永和路73之2號','永和路117號');

COMMIT;