DECLARE

--新北市中和區福善里36鄰永和路67號
--新北市中和區福善里36鄰永和路81號
V_ORI_ADDR VARCHAR2(4000 CHAR) := '新北市中和區福善里永和路67-1號五樓';

V_MATCH_PATTERN VARCHAR2(4000 CHAR) := '新北市中和區福善里永和路67之1號五樓';
V_MATCH_PATTERN_2 VARCHAR2(4000 CHAR) :=REGEXP_REPLACE(V_MATCH_PATTERN,'之','-');
V_MATCH_PATTERN_3 VARCHAR2(4000 CHAR) := REGEXP_REPLACE(V_MATCH_PATTERN,'樓','F');


V_REPLACE_FROM VARCHAR2(4000 CHAR) :='永和路67之1號五樓';
V_REPLACE_FROM_2 VARCHAR2(4000 CHAR) := REGEXP_REPLACE(V_REPLACE_FROM,'之','-');
V_REPLACE_FROM_3 VARCHAR2(4000 CHAR) := REGEXP_REPLACE(V_REPLACE_FROM,'樓','F');


V_REPLACE_TO   VARCHAR2(4000 CHAR) := '永和路83號五樓';
V_REPLACE_TO_2   VARCHAR2(4000 CHAR) := REGEXP_REPLACE(V_REPLACE_TO,'之','-');
V_REPLACE_TO_3   VARCHAR2(4000 CHAR) := REGEXP_REPLACE(V_REPLACE_TO,'樓','F');

V_AFTER_ADDR VARCHAR2(4000 CHAR) := '新北市中和區福善里永和路81號';

V_RESULT VARCHAR2(1000 CHAR) := '';


-------------------------- 內部函數 ----------------------------


   --數字轉中文數字(3 -> 三)
   function FN_number_To_Ch_number(
   v_input_number IN VARCHAR2
   )return varchar
   IS
   begin
   RETURN SUBSTR('一二三四五六七八九',v_input_number,1);
   end;


BEGIN
DBMS_OUTPUT.PUT_LINE('======== TEST START =========');



DBMS_OUTPUT.PUT_LINE('------------ PATTERN --------------');
DBMS_OUTPUT.PUT_LINE('V_MATCH_PATTERN:' || V_MATCH_PATTERN);
DBMS_OUTPUT.PUT_LINE('V_MATCH_PATTERN_2:' || V_MATCH_PATTERN_2);
DBMS_OUTPUT.PUT_LINE('V_MATCH_PATTERN_3:' || V_MATCH_PATTERN_3);

DBMS_OUTPUT.PUT_LINE('------------ REPLACE_FROM --------------');
DBMS_OUTPUT.PUT_LINE('V_REPLACE_FROM_2:' || V_REPLACE_FROM_2);
DBMS_OUTPUT.PUT_LINE('V_REPLACE_FROM_3:' || V_REPLACE_FROM_3);

DBMS_OUTPUT.PUT_LINE('------------ REPLACE_TO --------------');

DBMS_OUTPUT.PUT_LINE('V_REPLACE_TO_2:' || V_REPLACE_TO_2);
DBMS_OUTPUT.PUT_LINE('V_REPLACE_TO_3:' || V_REPLACE_TO_3);

IF REGEXP_LIKE(V_ORI_ADDR,V_MATCH_PATTERN)  THEN

  DBMS_OUTPUT.PUT_LINE('<case0>符合原始轉換！！');
  DBMS_OUTPUT.PUT_LINE('轉換前:'  || V_ORI_ADDR);
  SELECT REGEXP_REPLACE (V_ORI_ADDR,V_REPLACE_FROM,V_REPLACE_TO) INTO  V_RESULT FROM DUAL;
  DBMS_OUTPUT.PUT_LINE('轉換後:' || V_RESULT);

ELSIF REGEXP_LIKE(V_ORI_ADDR,V_MATCH_PATTERN_2) THEN
  DBMS_OUTPUT.PUT_LINE('<case1>符合之字轉換！！');
  DBMS_OUTPUT.PUT_LINE('轉換前:'  || V_ORI_ADDR);
  SELECT REGEXP_REPLACE (V_ORI_ADDR,V_REPLACE_FROM_2,V_REPLACE_TO_2) INTO  V_RESULT FROM DUAL;
  DBMS_OUTPUT.PUT_LINE('轉換後:' || V_RESULT);

ELSIF REGEXP_LIKE(V_ORI_ADDR,V_MATCH_PATTERN_3) THEN
  DBMS_OUTPUT.PUT_LINE('<case2>符合F字轉換！！');
  DBMS_OUTPUT.PUT_LINE('轉換前:'  || V_ORI_ADDR);
  SELECT REGEXP_REPLACE (V_ORI_ADDR,V_REPLACE_FROM_3,V_REPLACE_TO_3) INTO  V_RESULT FROM DUAL;
  DBMS_OUTPUT.PUT_LINE('轉換後:' || V_RESULT);
END IF;





DBMS_OUTPUT.PUT_LINE('======== TEST END =========');
END;
/
